### PR TITLE
Genesis DAO Playground

### PR DESCRIPTION
**Pull request by dOrgJelli**
The creation of this DAO was requested so the Genesis community could test new DAO configurations without messing with the main Genesis DAO.

image

### CODE REVIEW

**Review by orenyodfat — COMMENTED** [review]
How about playing in rinkeby ?
How about using arc v19?

**Comment by dOrgJelli** [comment]
Pat had requested this be mainnet, I'll let him explain his reasoning there.

Whoops, I accidentally used the v16 migration script. Would you recommend it be redeployed / migrated to v19?

**Comment by orenyodfat** [comment]
> Whoops, I accidentally used the v16 migration script. Would you recommend it be redeployed / migrated to v19?

Yes.  as it use [infra 0.0.1-rc.14](https://github.com/daostack/infra/releases/tag/0.0.1-rc.14)

**Comment by papa-raw** [comment]
Hey guys,

After having a convo/thinking it over Rinkleby is fine.

Thanks

**Pull request closed without merging**
